/*
HEAP SORT
1. ARRAY AS A BINARY TREE;
    ->GIVEN ARRAY => TREAT IT AS A COMPLETE BINARY TREE 
    -> INDEX RULE :
                    LEFT CHILD: 1i +1;
                    RIGHT CHILD: 1i +1;
2. BUILD MAX HEAP
    ->NEED TO START FROM LAST NON-LEAF NODE;
        LAST NON-LEAF = (N-1)-1;
    ->APPLY HEAPIFY FROM BOTTOM TO TOP;
        PARENT->LEFT;
        PARENT->RIGHT;
3. SWAP ROOT WITH LAST ELEMENT;
    ->ROOT CONTAINS MAX ELEMENTL;
    ->SWAP IT WITH THE LAST ELEMENT OF THE HEAP;
4. REDUCE HEAP SIZE;
    ->REDUCE HEAP SIZE BY 1;
    ->THE LAST ELEMENT IS NOW IN ITS CORRECT SORTED POSITION;
5. HEAPIFY THE ROOT
    ->RESTORE MAX-HEAP PROPERTY FROM ROOT(INDEX 0)
6. REPEAT
    ->REPEAT STEPS 3 - 5 UNITL HEAP SIZE BECOMES 1


EXAMLPE:
    [4,10,5,3,1]
1.
        10
    5       3      ===>>  [10,5,3,4,1]
4      1

2.
    [1,5,3,4,10]

    HEAP SIZE =4;
    HEAPIFY = [5,4,3,1,10]
    SWAP 5 & 1 [1,4,3,5,10]
    HEAP SIZE =3
    HEAPIFY = [4,3,1,5,10]
    SWAP 4 & 1 = [1,3,4,5,10]
    
*/